### ISSUE TITLE
Issues with Docker images

### ISSUE THREAD

**Issue by j99ht** [ishkin/Proton#14]
Hi,

When I try to run the image I'm getting the following errors

WARNING: Problem with directory [/usr/share/tomcat7/common/classes], exists: [false], isDirectory: [false], canRead: [false]
Oct 07, 2015 11:26:31 AM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/common], exists: [false], isDirectory: [false], canRead: [false]
Oct 07, 2015 11:26:31 AM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/server/classes], exists: [false], isDirectory: [false], canRead: [false]
Oct 07, 2015 11:26:31 AM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/server], exists: [false], isDirectory: [false], canRead: [false]
Oct 07, 2015 11:26:31 AM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
Oct 07, 2015 11:26:31 AM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/shared], exists: [false], isDirectory: [false], canRead: [false]
Oct 07, 2015 11:26:31 AM org.apache.catalina.startup.Catalina initDirs
SEVERE: Cannot find specified temporary folder at /var/lib/tomcat7//temp
Oct 07, 2015 11:26:32 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Oct 07, 2015 11:26:32 AM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 947 ms
Oct 07, 2015 11:26:32 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Oct 07, 2015 11:26:32 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.52 (Ubuntu)
Oct 07, 2015 11:26:32 AM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /etc/tomcat7/Catalina/localhost/manager.xml
Oct 07, 2015 11:26:33 AM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /etc/tomcat7/Catalina/localhost/host-manager.xml
Oct 07, 2015 11:26:33 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/ProtonOnWebServerAdmin.war
Oct 07, 2015 11:26:34 AM com.ibm.hrl.proton.admin.webapp.ProtonAdminServletContextListener contextInitialized
INFO: initializing ProtonAdminServletContextListener
Oct 07, 2015 11:26:34 AM com.ibm.hrl.proton.admin.webapp.ProtonAdminServletContextListener contextInitialized
INFO: created popertiesFileInputStream = java.io.ByteArrayInputStream@23848630
Oct 07, 2015 11:26:34 AM com.ibm.hrl.proton.admin.webapp.ProtonAdminServletContextListener contextInitialized
INFO: getServletContext().getRealPath(/) = /var/lib/tomcat7/webapps/ProtonOnWebServerAdmin/
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Oct 07, 2015 11:26:35 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/ProtonOnWebServer.war
Oct 07, 2015 11:26:36 AM com.ibm.hrl.proton.webapp.ProtonServletContextListener contextInitialized
INFO: initializing ProtonServletContextListener
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Oct 07, 2015 11:26:36 AM com.ibm.hrl.proton.webapp.ProtonServletContextListener$1 run
INFO: context real path = /var/lib/tomcat7/webapps/ProtonOnWebServer/
Oct 07, 2015 11:26:36 AM com.ibm.hrl.proton.server.executor.PropertiesParser loadProperties
INFO: Properties are : 
 metadatFile =/EmptyDefinition.json 
 inputPortNumber =3002 
 outputPortNumber =3302
Oct 07, 2015 11:26:36 AM com.ibm.hrl.proton.webapp.ProtonServletContextListener$1 run
INFO: init: initializing metadata and all the system singletons
Oct 07, 2015 11:26:36 AM com.ibm.hrl.proton.webapp.ProtonServletContextListener$1 run
INFO: init: done initializing metadata, returned the following exceptions: 
Oct 07, 2015 11:26:36 AM com.ibm.hrl.proton.webapp.ProtonServletContextListener$1 run
INFO: init: done initializing singletons , starting the servers...
Oct 07, 2015 11:26:36 AM com.ibm.hrl.proton.server.adapter.OutputServer run
INFO: Proton output server started, listening on output port: 3302
Oct 07, 2015 11:26:36 AM com.ibm.hrl.proton.server.adapter.InputServer run
INFO: Proton server Started, listening on port: 3002
Oct 07, 2015 11:26:36 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/AuthoringToolWebServer.war
Oct 07, 2015 11:26:37 AM org.apache.catalina.loader.WebappClassLoader validateJarFile
INFO: validateJarFile(/var/lib/tomcat7/webapps/AuthoringToolWebServer/WEB-INF/lib/javax.servlet-api-3.1.0.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Oct 07, 2015 11:26:37 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/AuthoringTool.war
Oct 07, 2015 11:26:39 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /var/lib/tomcat7/webapps/ROOT
Oct 07, 2015 11:26:40 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Oct 07, 2015 11:26:40 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 7499 ms

Despite of it seems the server has started I cannot access to http://localhost:8080/AuthoringTool/Main.html

Is there any issue with the Docker files?

Thanks

**Comment by ishkin** [comment]
Hello, all the messages in the log confirm to standard initialization, therefore there should be no problem with the initialization of the AuthoringTool application. 
Could you confirm to me that you are trying to access the http://localhost:8080/AuthoringTool/Main.html from the same ip address the tomcat installation is running on? 
Otherwise you have to use the whole URL (http://<ip address of the tomcat machine>:8080/AuthoringTool/Main.html

Thank you!

**Comment by j99ht** [comment]
Thanks for your prompt response.

Yes, I can confirm I am trying from the same ipaddress. Even I have used also 127.0.0.1 and the ips assigned to docker and the ip assigned by our router.

Thanks, but I always get this
![image](https://cloud.githubusercontent.com/assets/13207577/10338212/18953ff0-6d05-11e5-9ec0-62970bd1ba1c.png)

**Comment by andreimarinescu** [comment]
Are you using the latest version of the Dockerfile? What happens if you access /AuthoringTool directly?

**Comment by j99ht** [comment]
I downloaded the files yesterday morning, so I guess I am using the latest version.

Same error accessing to /AuthoringTool directly

Thanks

**Comment by andreimarinescu** [comment]
Please note that I'm not one of the official members of the Proton team. I did however develop the Dockerfile. (just FYI).

I just cloned the latest master of this repo, and ran the following commands, while in the docker folder:

     $ docker build -t proton_test --no-cache=true .
     $ docker run --rm -p 8080:8080 proton_test

This resulted in a working AuthoringTool instance (screenshot below).
![screenshot from 2015-10-07 16 35 37](https://cloud.githubusercontent.com/assets/1049591/10338995/d25729ec-6d11-11e5-87d6-1680c4af391a.png)

**Comment by j99ht** [comment]
Thanks, now it works. I was missing to specify the port.

Thanks for your help

**Comment by talhaham** [comment]
Andrei, thank you for this help!

2015-10-07 16:43 GMT+03:00 j99ht <notifications@github.com>:
