### ISSUE TITLE
The key [Name] was not in the map, reason: The key [Name] was not in the map

### ISSUE THREAD

**Issue by j99ht** [ishkin/Proton#15]
Hi,

I was trying to integrate Proton with Orion, but when Orion is sending events to Proton, I always get the same error:

com.ibm.hrl.proton.webapp.providers.EventJSONMessageReader readFrom
SEVERE: Could not parse json event org.apache.wink.json4j.JSONException: The key [Name] was not in the map, reason: The key [Name] was not in the map

I have reviewed the attributes names and they are OK.

See below the attrNames seen by Cygnus (already integrated with Orion)
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | Altitude         | integer  | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | AltitudeDelta1   | integer  | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | AltitudeDelta2   | integer  | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | BatteryLevel     | integer  | 25        | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | CO               | integer  | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | COCal            | float    | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | CurrentRSSI      | integer  | -110      | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | LastPacketRSSI   | integer  | -40       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | LastPacketSNR    | integer  | 8         | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | Latitude         | float    | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | LatitudeDelta1   | integer  | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | LatitudeDelta2   | integer  | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | Longitude        | float    | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | LongitudeDelta1  | integer  | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | LongitudeDelta2  | integer  | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | NO               | integer  | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | NO2              | integer  | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | NO2Cal           | float    | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | NOCal            | float    | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | Ozone            | integer  | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | OzoneCal         | float    | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | Serial           | float    | 25        | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | Speed            | integer  | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | SpeedDelta1      | integer  | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | SpeedDelta2      | integer  | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | humidity         | integer  | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | humidityCal      | float    | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | pressure         | integer  | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | pressureCal      | float    | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | temperature      | integer  | 33        | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | temperatureCal   | float    | 23        | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | timestamp        | integer  | 140021212 | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | timestampDelta   | integer  | 720       | []     |
| 1444683578 | 2015-10-12T20:59:38.352 | sensor4  | STCSensor  | timestampDelta2  | integer  | 23        | []     |
+------------+-------------------------+----------+------------+------------------+----------+-----------+--------+

I also attach the project json exported. 

![image](https://cloud.githubusercontent.com/assets/13207577/10439031/99c76716-7137-11e5-813a-074eae8fea74.png)

Can you help me out please?

Thanks beforehand

**Comment by talhaham** [comment]
Hi,

Since we are having many users and many CEP questions, we started to
document our answers in StackOverflow to help us and our users community.
It would be very helpful for us and the community if you could post this
question *there* <http://stackoverflow.com/>. If you agree, please send me (
tali@il.ibm.com) the link to your question, and I will post the answer
there. Please add the fiware, cep tags. Thank you very much in advanced!

Tali Yatzkar Haham

2015-10-13 0:19 GMT+03:00 j99ht <notifications@github.com>:

**Comment by j99ht** [comment]
Please see below

http://stackoverflow.com/questions/33096357/cep-proton-the-key-was-not-in-the-map-reason-the-key-was-not-in-the-map

Thanks beforehand

**Comment by talhaham** [comment]
Thank you!
I answered you there

2015-10-13 10:15 GMT+03:00 j99ht <notifications@github.com>:

**Comment by talhaham** [comment]
Dear j99ht,

Thank you for posted at Stackoverflow. I think we solved there your original issue of using xml format and having the expected event name and attributes. Your current issue is different and it is difficult to handle without communication. Could you please:
1. Stop tomcat
2. Delete tomcat log file (under logs)
3. Start tomcat
4. Perform the action you want to perform
5. Write me what action you took, send me the whole log file and your definition file to tali@il.ibm.com

I will create a FIWARE jira issue from it. And hopefully we could solve your issue.

 Thanks,
Tali

**Comment by mafg** [comment]
I have run in the same issue with the Docker instance.
Deploying Proton on a tomcat7 instance in a localmachine (with Debian8), all work fine. Just, followed the official [guide] (https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/CEP_GE_-_Proactive_Technology_Online_Installation_and_Administration_Guide#Configuring_the_administration_application).

But I have noticed that the following parts are missing in the catalina.out of the Docker instance:

com.ibm.hrl.proton.server.executor.PropertiesParser loadProperties
INFO: Properties are : 
 metadatFile =/tmp/defs/DoSAttack.json 
 inputPortNumber =3002 
 outputPortNumber =3302

Thanks,
Marco

**Comment by talhaham** [comment]
Thank you Marco.

I updated the docker file to take the wars from the new artifacts directory
as you suggested in Stackoverflow.
I'm not sure why it has any affect, since the wars should be the same, but
it is better to take them form the artifacts directory without worry on
removing their version name.
Thanks,
Tali

2015-10-26 17:11 GMT+02:00 Marco <notifications@github.com>:

**Comment by dethos** [comment]
Given that the [XML messages from Orion are deprecated](https://github.com/telefonicaid/fiware-orion/blob/develop/doc/manuals/deprecated.md), when will the integration with Orion start using JSON instead of XML, or at least accept the JSON format?

**Comment by talhaham** [comment]
We need to discuss with the Orion team and our dev team when we can change
the integration with Orion to support Orion's JSON format.

The CEP supports JSON format for input and output events, but this JSON
format is not the NGSI JSON format used by Orion.

2016-01-20 19:05 GMT+02:00 Gonçalo Valério <notifications@github.com>:
