### ISSUE TITLE
jar not loaded

### ISSUE THREAD

**Issue by j99ht** [ishkin/Proton#23]
Hi, I have deployed the app on Ubuntu 14.04, tomcat 7 and java 8:
Java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

When tomcat7 starts, we can see the following in the logs

INFO: validateJarFile(/var/lib/tomcat7/webapps/AuthoringToolWebServer/WEB-INF/lib/javax.servlet-api-3.1.0.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class

Can anybody help on this?

Thanks beforehand

**Comment by talhaham** [comment]
This INFO message is normal. It doesn't indicate an error. You can ignore
it.

2015-11-11 12:14 GMT+02:00 j99ht <notifications@github.com>:
