### ISSUE TITLE
CEP Docker: unable to locate REST adapter output port  

### ISSUE THREAD

**Issue by mafg** [ishkin/Proton#24]
Hi,
I'm running Proton in a docker container. I use the REST consumer, so I order to send events outside the container, the port used by the adapter needs to be exposed.
The only information available about the adapters ports, wiki or Programmer Guide, refers to the input and output ones used for the communications with Proton (usually 3302,3002).

Could be integrate this information in the guide, or are there other solutions?

Thanks,
Marco

**Comment by talhaham** [comment]
Marco,
Thos ports (usually 3302, 3002) are used for internal CEP communications
(between the CEP adapters and the CEP engine). They are not used for
sending events from the CEP to external consumer.

You define the URL (with the port) that is used to send events via REST in
the CEP consumer definition.
You can see example for it in the *CEP user guide* *appendix*, in the
screenshot that gives example for such REST consumer definition.

Regards,
Tali

2015-11-12 13:04 GMT+02:00 Marco <notifications@github.com>:

**Comment by mafg** [comment]
Thanks for your reply Tali.

I read the appendix, and the REST output works fine as long as I handle it inside the docker container. 

Here my scenario:
Proton is running inside a docker container in a host machine.
In order to get the access to the tomcat server from a remote machine, the server port (8080) in the docker container is mapped on a port of the host machine.
So, being my REST service located in a remote machine, I thought to do the same for the REST adapter ouput port.

I don't know if this is the right solution, maybe there're other ways.

Thanks,
Marco.

**Comment by mafg** [comment]
I was trying to send the REST event to an accumulation server running in the local machine. ProntI have got the following error:

> INFO: events sent to proton runtime...
org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection refused
org.apache.commons.httpclient.HttpMethodDirector executeWithRetry

By changing the URL with a remote host IP (e.i. http://posttestserver.com/post.php), instead of localhost, all worked fine.
I don't know why, but maybe there are some kind of conflicts using the localhost.

Thanks!
