### ISSUE TITLE
Current Dockerfile fails to build a usable proton image.

### ISSUE THREAD

**Issue by dmabtrg** [ishkin/Proton#34]
When I try to build the docker image I don't get any errors but the resulting image does not have java, tomcat nor the proton app installed.  Here's the output of the build command:

https://gist.github.com/dmabtrg/27749cb2a42caf53153b

**Comment by urishani** [comment]
Strange, the image i pushed was created with that dockerfile and it is 
fully functional, albeit with some hiccups we work around.
Need to check it again with our developer (in cc:)

Thanks for the heads up.
- Uri

**Comment by urishani** [comment]
Fixed already.
