### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by drasko** [ishkin/Proton#35]
Hello,
can you please make a Docker image and push it to official Fiware Docker Hub: https://hub.docker.com/u/fiware

Please tag the image when pushing, so we can use a specified release tag in our `docker-compose` files.

**Comment by urishani** [comment]
Hi,
We have done that last month. This is our image: 
https://hub.docker.com/r/fiware/proactivetechnologyonline/
It already had > 30 pulls.
It appears in the list for the link you provided - one before last on it.
I noticed that the README.md info was not uptodate and I updated it.

Let me know if i need to do anything more.
Thanks,
- Uri

**Comment by urishani** [comment]
OK. I now see the problem in the URL I am using. Will fix that.

**Comment by urishani** [comment]
This seems to be ok as commented above. CEP Proton is published similarly to the other GEis of FIWARE Data.
