### ISSUE TITLE
Update Docker image README.md.

### ISSUE THREAD

**Issue by dmabtrg** [ishkin/Proton#36]
The latest changes made to the Dockerfile makes some of the instructions to create and run the container obsolete:

- There's no need to run the container in privileged mode nor to add the SYS_PTRACE capability.  This was needed when using the ubuntu image as base in order to install and run tomcat.  The tomcat base image used now does not need it.

- The container automatically starts tomcat and outputs the logs to stdout, so there's no need to run the `tail -f /dev/null` command.

- The `-p 8080:8080` maps the `8080` port to `localhost`, so the user can use `http://localhost:8080` to access the tomcat server.

Thanks.

**Comment by urishani** [comment]
Great advice. I will remove these right away. thanks for watching over me.
- Uri
