### ISSUE TITLE
Wrong Docker badge at README.md

### ISSUE THREAD

**Issue by albertinisg** [ishkin/Proton#38]
Checking the badges of the repository, I've found that the bag you are displaying (image) is actually the one from Orion:

[![Docker badge](https://img.shields.io/docker/pulls/fiware/orion.svg)](https://hub.docker.com/r/fiware/proactivetechnologyonline/)

Meanwhile it should be:

[![Docker badge](https://img.shields.io/docker/pulls/fiware/proactivetechnologyonline.svg)](https://hub.docker.com/r/fiware/proactivetechnologyonline/)

**Comment by urishani** [comment]
Hi Alberto,
The two links you provide in your mail are the same.
So - I dont know what is wrong to be fixed.

Thanks,
- Uri

**Comment by albertinisg** [comment]
The links are the same, but not the image (please see issue in Github: https://github.com/ishkin/Proton/issues/38#issue-151433802). 

The badge you are actually displaying points to:
https://img.shields.io/docker/pulls/fiware/orion.svg

But it should point to:
https://img.shields.io/docker/pulls/fiware/proactivetechnologyonline.svg

**Comment by urishani** [comment]
Thanks. Done.

**Comment by urishani** [comment]
Fixed. Thanks.
