### ISSUE TITLE
Array Condition within EPA CEP PROTON

### ISSUE THREAD

**Issue by j99ht** [ishkin/Proton#40]
Using CEP Proton I want to check if, for the events received in a time interval, the id of the second and following events is contained in an attribute of type array coming in the first event. Let's say the first event is coming with the attribute called group that is an array of integers (10, 20, 30). The following events will come with an id, ex 20, 25 and so on. I want to check if the id of those events is included in the attribute group included in the first event. For that I have created a condition in EPA

ArrayContains(ArrayGet(myevent.group,0),ArrayGet(myevent.id,ArraySize(myevent.id)-1))
However I'm getting an error when I click on verify

Error   Error in  EPA: expression error of undefined    myepa
Am I doing anything wrong? Cannot I access to the attribute array using ArrayGet? Or maybe ArrayContains cannot work with the result of ArrayGet?

**Comment by urishani** [comment]
This issue is processed over this stackoverflow thread: [http://stackoverflow.com/questions/39774810/array-condition-within-epa-cep-proton](url).

**Comment by urishani** [comment]
fixing this url here:
[http://stackoverflow.com/questions/39774810/array-condition-within-epa-cep-proton](http://stackoverflow.com/questions/39774810/array-condition-within-epa-cep-proton)
