### ISSUE TITLE
Fiware-Service and Fiware-Servicepath Headers

### ISSUE THREAD

**Issue by thomaskoeck** [ishkin/Proton#42]
Hi,

I have a question regarding the support of Fiware-Service and Fiware-Servicepath headers in Proton. I found out in Stackoverflow that per March 2016 these two headers could not be set using Proton. I wonder if this changed by now? I could not find any more recent information about that. If it is still not yet supported by Proton, how is Proton supposed to get data from Orion that is under a specific Fiware-Service and Fiware-Servicepath and how can Proton assign events to the correct entity in Orion?

Thanks in advance for your help.

Best regards,
Thomas

**Comment by ishkin** [comment]
Hi,
Proton doesn't support those headers. 
To remind you, those headers are optional, to quote from Orion's documentation : 
"Fiware-ServicePath is an optional header. It is assumed that all the entities created without Fiware-ServicePath (or that don't include service path information in the database) belongs to a root scope "/" implicitely."

The development of Proton is frozen , so adding this feature is not on the table, 

However,having said that,  Proton's code is open source and can be downloaded from the git and adapted to your needs.
